### ISSUE TITLE
Improve import_wiz.py UI - Presets tab

### ISSUE THREAD

**Issue by robertgodfrey** [DARC-UHM/Data-Processing-Scripts#12]
- It's difficult to understand the flow of required input, and optional fields
- There are order of priority and dependencies in the input fields
- Group them by adding background color/spacing
- Doesn't support Mac OSX Night Shift / dark display (hover text / button colors are not inverting properly)
- Vertical scroll area is not defined or is unclear

**Comment by boahelenshin** [comment]
use this library: https://github.com/israel-dryer/ttkbootstrap/

**Comment by boahelenshin** [comment]
Check list
 1. Vertically stack three boxes
  - Preset list
  - Editing currently selected preset
  - Editing current file template

 2. allocate a scroll bar vertically for the whole canvas
 remove the scroll bar vertical on the Editing current file template

 3. Header for each three boxes.
  - Header title
  - border
  - spacing

**Comment by ninabrissey** [comment]
Suggestions for UI Mock-ups from NA Beach and TW Frontend Community internal Thoughtworks chat groups:
- Figma 
- Connect with Tanya Randstoft for quick React mock-up (Nina for learning whether we go this direction or not)
- Balsmiq for lightweight
