### ISSUE TITLE
format_and_worms.py returning questionable taxonomy from WoRMS

### ISSUE THREAD

**Issue by SarahRDBingo** [DARC-UHM/Data-Processing-Scripts#18]
Reviewing the WoRMS process in this python script has revealed that some of the original VARS concepts are not being matched to the proper taxon from WoRMS rest API. The three that seem to be mismatched are:

VARS "concept":
Asbestopluma (Asbestopluma) furcata
Asbestopluma (Asbestopluma) ruetzleri
Thouarella (Euthouarella) hilgendorfi

Python output for "ScientificName"
Asbestopluma furcata [https://marinespecies.org/aphia.php?p=taxdetails&id=1309488](url)
Asbestopluma [https://marinespecies.org/aphia.php?p=taxdetails&id=131893](url)
Thouarella hilgendorfi [https://marinespecies.org/aphia.php?p=taxdetails&id=1564339](url)

Expected output for "ScientificName"
Asbestopluma (Asbestopluma) furcata [https://marinespecies.org/aphia.php?p=taxdetails&id=133172](url)
Asbestopluma (Asbestopluma) ruetzleri [https://marinespecies.org/aphia.php?p=taxdetails&id=1023292](url)
Thouarella (Euthouarella) hilgendorfi [https://marinespecies.org/aphia.php?p=taxdetails&id=125413](url)

Some points of interest. All three of these VARS concept names contain a subgenus value (the stuff in parentheses), which are getting dropped. Two of the concept names from VARS are some how being matched to the WoRMS taxon with a status of "alternate representation" rather than "accepted". We only want to use taxa that have "accepted" status in WoRMS. I'm not sure if the python script itself is some how dropping the subgenus name from the concept and submitting the wrong name for request, or if simply the returns from the request to https://www.marinespecies.org/rest/ are wrong. The subsequent taxonomy fields for these records are populated using the aphiaID from the wrong taxon being pulled (see links above). 

I'm wondering if all concepts containing a subgenus are being treated the same way. The records that started with the VARS concept "Asbestopluma (Asbestopluma) ruetzleri" was only matched to the genus level and the species information was some how parsed into the Morphospecies field as "Asbestopluma; ruetzleri". On the flip side the VARS concept "Asbestopluma (Asbestopluma) furcata" was matched to the species level and the Morphospecies field is populated as "Asbestopluma", which is unnecessary. 

Related problems in output file:
- 'VernacularName' column in the output file is not currently not populated with any value.
- 'VernacularNameCategory' is sometimes populated with incorrect value.
- 'TaxonRank' column is often populated with incorrect value.
- 'Morphospecies': seems to be adding extra information eg. row 481 adds 'Asbestopluma' when should be 'NA'
- 'CombinedNameID' val not populating as expected eg. row 481 populates as 'Asbestopluma furcata Asbestopluma' when val should be 'Asbestopluma (Asbestopluma) furcata'

**Comment by Coltonmw** [comment]
This seems like a symptom. We want to be able to validate these issues and we think we have a fix that needs to be spiked out. We'll keep this open until we create that spike, then either this card can be converted to the spike or the information here can live within that spike, TBD. Not currently in play.
