### ISSUE TITLE
format_and_worms.py: Need to pull 'Synonym' values from VARS knowledgebase

### ISSUE THREAD

**Issue by robertgodfrey** [DARC-UHM/Data-Processing-Scripts#23]
'Synonym' values need to be pulled from the VARS Knowledgebase (not from WoRMS). Use VARS kb API eg. http://hurlstor.soest.hawaii.edu:8083/kb/v1/concept/Actinopterygii

**Comment by robertgodfrey** [comment]
Tentative working solution in [issue-23-synonyms](https://github.com/DARC-UHM/Data-Processing-Scripts/tree/issue-23-synonyms) branch. Need to wait for DARC's local VARS knowledge base to be updated.

**Comment by boahelenshin** [comment]
an example with a complex list of synonyms https://www.marinespecies.org/aphia.php?p=taxdetails&id=207326#specimens
