### ISSUE TITLE
Combine Settings and Convert tab 

### ISSUE THREAD

**Issue by ninabrissey** [DARC-UHM/Data-Processing-Scripts#25]
**User Journey:**
**Given** I am processing EX files 
EX1706_CTD_cnv and Tracking/EX1706Tracking_raw
WHEN I Enter Cruise Number as EX1706
AND I Enter Dive Number as DIVE01
AND base directory path: {your absolute path} 01_Import_Sensor_Data/Test_Files / 
AND 
I put in output path as: vars/dataarchive/{OUT}/{CRUISE}_{DIVE}_{yyyymmdd}_ROVDATA.csv
**Then**It should generate an output file vars/dataarchive/D2/EX1706_DIVE01_20170710_ROVDATA.csv

**Given** I am processing NA files with 
**When** I put in my input path as 
AND 
I put in output path
**Then**I should generate an output file in the following folder

Associated Epic - #24

**Comment by ninabrissey** [comment]
GUI Convert tab in progress:

<img width="902" alt="Screen Shot 2023-02-20 at 12 15 51 PM" src="https://user-images.githubusercontent.com/80136642/220176624-8d0b4dc6-7e81-4c4a-b04b-9dd3a3919d31.png">

**Comment by boahelenshin** [comment]
Done as mob programming (2.20)
- tested NA flows with NA test data
- Definition of Altimeter: in relation to depth and distance from the ocean floor
- Added partial sample data from the NA114 folder from the FTP server
- null values and 0 values are valid scenarios, but are currently being flagged
- Noticed that the Presets tab has to be also manually changed to match NA formats
- dive reports from this folder was helpful to parse out some data (ftp://ftp.soest.hawaii.edu/hurlarchive/NA114/NA114/processed/dive_reports/H1783/H1783-report.pdf)
-

**Comment by boahelenshin** [comment]
GUI 
- the width of input/output folder needs to be bigger
- CLI version to see if it's simpler? [spike this?]

**Comment by ninabrissey** [comment]
- added a metrics folder to our [drive](https://drive.google.com/drive/folders/13f0WeoB_-Cyk9j9epymB81tcu46iURrl?usp=share_link) to document mouseclicks from beginning of iteration 0 to iteration 1

**Comment by ninabrissey** [comment]
Dev work is done.
