### ISSUE TITLE
STEP 0: Discover possibilities for QA/QC architectural improvements

### ISSUE THREAD

**Issue by fergmastaflex** [DARC-UHM/Data-Processing-Scripts#26]
As an engineer in this topsy-turvy world, I'd like to understand what resources are available to me.
We want to find out what we have at our disposal in order to best determine solutions for some of our upcoming challenges with QA/QC.

Specifically, we want to look into:

- Any space available for hosting (on premises server racks?)
- The team's comfort level in terms of maintaining online properties (aws lambdas, on prem server, etc)
    - If third-party tools are used, what would the budget look like for that? 
- What is the current process for documenting, and what improvements can be made to account for added complexity down the road.
- VARS schema and how it coincides with responses from WORMS
     - Understand the behavior during updates, creates and deletes
     - Understand the current state of DB management (if any) and what could potentially be added.
- Understand the current "caching" system and how that happens
    - How is it currently being interacted with
    - What's the schema in postgres for the "cache"
    - Are we able to get read access?

**Comment by boahelenshin** [comment]
https://obis.org/data/access/# - this has WORMS dump

**Comment by Coltonmw** [comment]
Take with us into inception/discovery.
