### ISSUE TITLE
[Spike] Determine if LifeWatch Belgium eLab tool can help solve the problem re: unaccepted status checks

### ISSUE THREAD

**Issue by Coltonmw** [DARC-UHM/Data-Processing-Scripts#28]
Ref: [](https://www.lifewatch.be/data-services/)

Scenario that reveals this problem is described in #18 

Context: 
Pre-requisite
1. Identify a list of animals that we need to do a quality check on given a list of video / reference id. 
2. Format this list of animals according to the website's expected input
3. Run the website's QA/QC 
4. Confirm the following validations from the results of the website
aphiaid_worms == valid_aphiaid_worms 
status_aphia_worms == accepted 
Any other records that do not meet these criteria, flag for update, and then update local copy with correct data. 

Things we need to learn:
1. How widespread is the problem? (how much of the data is out of sync in local copy?)
8. How can we solve this problem - (how do we update local cache?)

**Comment by boahelenshin** [comment]
[result_demofile_lifewatch_marine.txt](https://github.com/DARC-UHM/Data-Processing-Scripts/files/10819389/result_demofile_lifewatch_marine.txt)

sample output from the QA/QC process on the website
