### ISSUE TITLE
[SPIKE] - CLI prototype

### ISSUE THREAD

**Issue by ninabrissey** [DARC-UHM/Data-Processing-Scripts#30]
For stakeholders to make decision on CLI vs GUI

- pros/cons

AC:
- Process EX files
- Can apply overrides 
- Output will be a dummy file

**Comment by oac1771** [comment]
Refactor ideas:
    - Make config class take in class called FileReader (or something) that reads file_settings
        and override_settings so Config can be tested a bit easier without mocking reading file
    - create classes to handle preprocessing of specific file types 
    - get setting values from config object only instead of reading from config.settings.get...
