### ISSUE TITLE
qaqc_and_output.py KeyError: ʻancillary_dataʻ 

### ISSUE THREAD

**Issue by SarahRDBingo** [DARC-UHM/Data-Processing-Scripts#6]
@Kangasaur The program was able to fetch and format records for the first handful of dives from the video sequence list: 

Deep Discoverer 14040201
Deep Discoverer 14040202
Deep Discoverer 14040203
Deep Discoverer 14040301
Deep Discoverer 14040302
Deep Discoverer 14040303
Deep Discoverer 14040304 

Program quit during or after fetching WoRMS taxonomy for "Deep Discoverer 14040305". The traceback that was given:

Fetching Deep Discoverer 14040305
Getting deployment(s) from HURL database...
641 annotations found
Formatting records...
Getting info for new concept: Anthoptilum grandiflorum
Getting info for new concept: Tubulariidae
Getting info for new concept: Iridogorgia sp
Getting info for new concept: Holothuroidea
Getting info for new concept: Gonostomatidae
Getting info for new concept: Colossendeis sp
Getting info for new concept: Stauropathes sp
Getting info for new concept: Ptilella inflata
Getting info for new concept: Metallogorgia melanotrichos
Getting info for new concept: Ophiocreas oedipus
Getting info for new concept: Bathydorus sp
Getting info for new concept: Paulasterias sp
Getting info for new concept: Narella sp
Getting info for new concept: Hemicorallium sp white
Getting info for new concept: Galacantha rostrata
Getting info for new concept: Sibopathes macrospina
Getting info for new concept: Ilyophis sp
Getting info for new concept: Paelopatides sp
Getting info for new concept: Ophiuridae
Getting info for new concept: Chromista
Getting info for new concept: Calyptrophora sp
Getting info for new concept: Hydrolagus affinis
Getting info for new concept: Iridogorgia magnispiralis
Getting info for new concept: Paguridae
Getting info for new concept: Neolithodes sp
Getting info for new concept: Benthopectinidae
Getting info for new concept: Thaumatocrinus sp
Getting info for new concept: Primnoidae
Getting info for new concept: Antedonoidea
Getting info for new concept: Hydrozoa
Getting info for new concept: Hymenaster sp
Getting info for new concept: Chrysogorgia sp
Traceback (most recent call last):
  File "/Users/darc/workspace/Data-Processing-Scripts/bin/etc/python/qaqc_and_output.py", line 627, in <module>
    record_dict['Latitude'] = annotation['ancillary_data']['latitude']
KeyError: 'ancillary_data'

When this error is returned, the program stops and no progress is saved. Iʻm not sure why ancillary_data is missing for this deployment, or is it a record-specific key?

The same error was returned when the program reached dive "Deep Discoverer 14040308" after getting info for new concept "Lebbeus sp"

**Comment by robertgodfrey** [comment]
I think that is correct. We just need to make sure to run the `darc_merge_nav_ctd.sh` before running this script. I'll make a note of this and close this issue.
