### ISSUE TITLE
Some modifications to qaqc_and_outputs.py .TSV output fields

### ISSUE THREAD

**Issue by SarahRDBingo** [DARC-UHM/Data-Processing-Scripts#9]
Please do all work for this issue in the [issue-9-qaqc-outputs](https://github.com/DARC-UHM/Data-Processing-Scripts/tree/issue-9-qaqc-outputs) branch.

Some of the DSCRTP fields need modifications to their outputs:

- [x] SampleID reports the video/imagecollection file name and elapsed time. We have decided to simpify the field to just video sequence name and UTC time.

- [x] AssociatedTaxa is reporting host name rather than associate concept name. Some associates are not mapping to the right host record if similar concept names are close in time. (eg ophiuroid associated with ʻDemospongiae tubeʻ seems to be placed as an associated taxa with a closer ʻDemospongiae encrustingʻ record, AND the concept reported in the AssociatedTaxa is Demospongiae(host) rather than ophiuroidea (associate)). Most of the concepts populated in the "associated taxa" actually look like hosts rather than the associated animal concept names. 

- [x] AphiaID field null values are reported as -1. Should be -999

- [x] Habitat null values are reported as "primarily: ". Should be NA

- [x] CMECSGeoForm is only applied to our initial "none" record. Should be applied to all records within the same video sequence name.

- [x] IdentifiedBy is using the VARS username verbatim, Should reformat to "Last name, First Name"

- [x] VerbatimSize is missing. Would like to populate this with our old size category bins from VARS

- [x] EventID is being populated as NA even though the EventID field in Dives.csv contains a value.

**Comment by robertgodfrey** [comment]
VerbatimSize incorrect for first row, need to relook
